### ISSUE TITLE
Game crashes for everyone except the server owner

### ISSUE THREAD

**Issue by Naehiro** [DST-Hamlet/PorkLand#719] opened 2024-10-06 01:57 UTC
### What happened? 发生了什么？

The world only loads for the person who created the server, and I think this may be due to incompatibility with certain client-side mods. The mods other players and I had enabled were:
- [Gesture Wheel](https://forums.kleientertainment.com/files/file/980-dst-gesture-wheel/)
- [Environment Pinger](https://steamcommunity.com/sharedfiles/filedetails/?id=2525858933)
- [Combined Status](https://forums.kleientertainment.com/files/file/1136-combined-status/)
- [Minimap HUD](https://forums.kleientertainment.com/files/file/352-minimap-hud/)
- [Server Size](https://steamcommunity.com/sharedfiles/filedetails/?id=795969984)
- [Skin Queue](https://forums.kleientertainment.com/files/file/1889-skin-queue/)
- [Zoom++](https://steamcommunity.com/sharedfiles/filedetails/?id=2837642411)

**Comment by Legend-Master** [comment] 2024-12-01 07:23
Do you have any log about the crash? I did a quick test but none of the mod you listed seem to cause crashes

**Comment by Naehiro** [comment] 2024-12-01 15:11
I wasn't able to find any log for either myself or those I was playing with.

**Comment by Legend-Master** [comment] 2024-12-02 01:36
Well, thanks for the report but I can't help much in that case, since I can't reproduce the crash, I'll close this for now, feel free to re-open if you find it crash again and can get some more info about it, you can find the log files in those locations by the way (get the log files before you re-open the game)

> https://support.klei.com/hc/en-us/articles/360029881191-Logs-and-Useful-Information-for-Bug-Reports-for-Don-t-Starve-Together

**Closed by Legend-Master** 2024-12-02 01:36 UTC
Labels: bug, mod conflict, needs verification
