### ISSUE TITLE
The world is looping

### ISSUE THREAD

**Issue by StepanTrof** [DST-Hamlet/PorkLand#585] opened 2024-09-04 19:49 UTC
### What happened?

The mayor of the city on the first island constantly tries to put the document on a pedestal, but the document is not put and the mayor tries again. It goes on endlessly. I hope this will be fixed.

**Comment by Ziwbi** [comment] 2024-09-04 19:54
Duplicate of #437

**Closed by Ziwbi** 2024-09-04 19:54 UTC
Labels: bug
